"""add course_name and photo_url to student

Revision ID: 5e5409b3feb1
Revises: 
Create Date: 2025-04-27 21:03:07.343926

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5e5409b3feb1'
down_revision = None
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('students',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('birth_date', sa.Date(), nullable=False),
#     sa.Column('course_name', sa.String(length=200), nullable=True),
#     sa.Column('photo_url', sa.String(length=500), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('students')
#     # ### end Alembic commands ###

"""add course_name and photo_url to student"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    # Step 1: Add the columns as nullable
    op.add_column('students', sa.Column('course_name', sa.String(200), nullable=True))
    op.add_column('students', sa.Column('photo_url', sa.String(500), nullable=True))

    # Step 2: Update existing rows with a default value
    op.execute("UPDATE students SET course_name = 'Default Course' WHERE course_name IS NULL")

    # Step 3: Make course_name non-nullable
    op.alter_column('students', 'course_name',
                    existing_type=sa.String(200),
                    nullable=False)


def downgrade():
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'course_name')
