"""Initial migration.

Revision ID: 80924a926e86
Revises: e1fcf6d13299
Create Date: 2025-05-09 14:16:15.591970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80924a926e86'
down_revision = 'e1fcf6d13299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('course_name')

    # ### end Alembic commands ###
